### ISSUE TITLE
Trouble with "Send To Layers" | Mac M1 Max 

### ISSUE THREAD

**Issue by reconroot** [NimaNzrii/comfyui-photoshop#43]
Hello. 

![CUI-PSD-Plugin-SendToLayers](https://github.com/NimaNzrii/comfyui-photoshop/assets/17152711/e3684613-7111-4e28-aad3-30305c5ce731)

I am having trouble with the "send to layers" feature.  As described in your presentation YouTube video; "if you press on the empty space on your plugin it will add the image as a layer".  Is there a setting I don't see that allows for this?  I am not sure if this is a Mac Photoshop issue versus the Windows.  Everything seems to be working fine except for this function. Video with Img-2-Img LCM "Render on Changes" and mouse clicks below.

https://github.com/NimaNzrii/comfyui-photoshop/assets/17152711/05b28585-16cb-430c-bc3a-5e52dc5e5e89

Thank-you for your plugin and assistance.

Mac M1 Max
32GB Ram
Latest Version of CC Photoshop 25.7.0 (Not the Beta)

**Comment by megated** [comment]
same here how does the send to layer work

**Comment by megated** [comment]
> same here how does the send to layer work

Mine resolve after updated my photoshop\

**Comment by reconroot** [comment]
> Mine resolve after updated my photoshop\

Hmm.. Still not working for me.
What version of Photoshop are you using? Are you on Mac @megated ? 
I see no new updates in CC today in stable.   "Send to layer" in both 25.7 and Beta 25.10 still not working for me. 

Thanks for any info.

**Comment by megated** [comment]
> > Mine resolve after updated my photoshop\
> 
> Hmm.. Still not working for me. What version of Photoshop are you using? Are you on Mac @megated ? I see no new updates in CC today in stable. "Send to layer" in both 25.7 and Beta 25.10 still not working for me.
> 
> Thanks for any info.

im on windows

**Comment by reconroot** [comment]
Thanks for clarifying @megated.  Perhaps a Mac issue.  Plugin renders in both stable and beta, but without the Send To Layers function.

**Comment by sergiuvacarescu** [comment]
Same here. PsS 2024 25.3.1
![Screenshot 2024-05-21 at 00 18 40](https://github.com/NimaNzrii/comfyui-photoshop/assets/12720807/67b3e7a0-b66f-4532-8714-b19341b048ea)

**Comment by aiaimimi0920** [comment]
I have encountered the same problem, upgrading the Photoshop version to 25 or higher.
The problem can be solved

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped

**Comment by benjaminv2** [comment]
tried V1.4.3 and V1.5.0 ,but send to layer still not working.
ver of Photoshop 24.0.0
